#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Sets up Developer ID signing + notarization for the fork's "T3 Code (V2)"
# macOS builds, which is what lets the installed app auto-update. Run it on a
# Mac, logged into gh as an account with admin on the fork:
#
#   curl -fsSL https://raw.githubusercontent.com/HexSleeves/t3code/dev/.github/v2-fork/setup-macos-signing.sh -o /tmp/setup-macos-signing.sh
#   bash /tmp/setup-macos-signing.sh
#
# Secrets go straight to GitHub. The private key and downloads stay in
# $WORKDIR (mode 700) until the last stage offers to delete them.

REPO="${REPO:-HexSleeves/t3code}"
export GH_REPO="$REPO" # the library's gh calls target this repository
APP_ID="com.$(printf '%s' "${REPO%%/*}" | tr '[:upper:]' '[:lower:]').t3code.v2"
WORKDIR="${WORKDIR:-$HOME/.t3-v2-signing}"
umask 077
mkdir -p "$WORKDIR"
ENV_FILE="$WORKDIR/wizard.env" # remembers non-secret answers between runs

# ask_file KEY "Prompt" reads a path to an existing file (drag it into the terminal).
ask_file() {
  local key="$1" prompt="$2" path
  while :; do
    ask "$key" "$prompt"
    path="${!key}"
    path="${path%\"}"; path="${path#\"}"; path="${path%\'}"; path="${path#\'}"
    path="${path%"${path##*[![:space:]]}"}"; path="${path/#\~/$HOME}"
    path="${path//\\ / }"
    if [[ -f "$path" ]]; then printf -v "$key" '%s' "$path"; return; fi
    warn "no file at: $path"
  done
}

TOTAL_STAGES=7

banner "T3 Code (V2): macOS signing for $REPO"

stage "Check tools and GitHub access"
say "Secrets are written to $REPO with gh, so it must be logged in as an admin there."
for tool in gh openssl curl base64; do
  command -v "$tool" >/dev/null 2>&1 || { warn "missing $tool; install it and re-run"; exit 1; }
done
if [[ "$(gh api "repos/$REPO" --jq .permissions.admin 2>/dev/null || true)" != "true" ]]; then
  warn "gh is not logged in with admin access to $REPO."
  step "Run: gh auth login   (or gh auth switch, if you have several accounts)"
  step "Log in as the account that owns $REPO, then re-run this wizard."
  exit 1
fi
note "gh can write secrets to $REPO. Files will be kept in $WORKDIR."
note "Apple's Developer ID steps need the Account Holder role on your team."
pause

stage "Find your Team ID"
open_url "https://developer.apple.com/account"
step "Scroll to Membership details and copy the Team ID (10 characters)."
while :; do
  ask APPLE_TEAM_ID "Team ID:"
  APPLE_TEAM_ID=$(printf '%s' "$APPLE_TEAM_ID" | tr '[:lower:]' '[:upper:]' | tr -d '[:space:]')
  [[ "$APPLE_TEAM_ID" =~ ^[A-Z0-9]{10}$ ]] && break
  warn "a Team ID is 10 letters or digits"
done
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"
set_var APPLE_TEAM_ID "$APPLE_TEAM_ID"

stage "Register the app's bundle ID"
open_url "https://developer.apple.com/account/resources/identifiers/add/bundleId"
step "Choose App IDs, Continue, then App, Continue."
step "Description: T3 Code V2"
step "Bundle ID: Explicit, $APP_ID"
step "Under Capabilities, tick Associated Domains (the app requests it for passkeys)."
step "Continue, then Register."
note "Already registered? Make sure Associated Domains is enabled on it, then move on."
pause "Press Enter once $APP_ID is registered"

stage "Create the Developer ID Application certificate"
if [[ -f "$WORKDIR/signing.key" ]]; then
  note "Reusing the private key and request from an earlier run."
else
  ask SIGNING_EMAIL "Email for the certificate request:"
  write_env SIGNING_EMAIL "$SIGNING_EMAIL"
  openssl req -new -newkey rsa:2048 -nodes \
    -keyout "$WORKDIR/signing.key" -out "$WORKDIR/signing.csr" \
    -subj "/emailAddress=$SIGNING_EMAIL/CN=T3 Code V2 signing/C=US" 2>/dev/null
  printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$WORKDIR/signing.csr"
fi
open_url "https://developer.apple.com/account/resources/certificates/add"
step "Choose Developer ID Application, Continue."
step "Profile Type: G2 Sub-CA (Xcode 11.4.1 or later), Continue."
step "Choose File: $WORKDIR/signing.csr, Continue, then Download."
ask_file CERT_PATH "Path to the downloaded .cer (drag it here):"
write_env CERT_PATH "$CERT_PATH"
openssl x509 -inform DER -in "$CERT_PATH" -out "$WORKDIR/signing.pem"
curl -fsSL https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer -o "$WORKDIR/ca.cer"
openssl x509 -inform DER -in "$WORKDIR/ca.cer" -out "$WORKDIR/ca.pem"
subject=$(openssl x509 -in "$WORKDIR/signing.pem" -noout -subject)
[[ "$subject" == *"Developer ID Application"* ]] || { warn "that is not a Developer ID Application certificate: $subject"; exit 1; }
if [[ "$(openssl x509 -in "$WORKDIR/signing.pem" -noout -pubkey)" != "$(openssl pkey -in "$WORKDIR/signing.key" -pubout)" ]]; then
  warn "the certificate was not issued for this wizard's request ($WORKDIR/signing.csr)."; exit 1
fi
CSC_KEY_PASSWORD=$(openssl rand -hex 24)
# SHA1/3DES keeps the .p12 importable by macOS `security`, which the build uses.
# LibreSSL (macOS's openssl) may reject -macalg but already defaults to SHA1.
p12_args=(pkcs12 -export -inkey "$WORKDIR/signing.key" -in "$WORKDIR/signing.pem"
  -certfile "$WORKDIR/ca.pem" -name "T3 Code V2 Developer ID"
  -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES
  -passout "pass:$CSC_KEY_PASSWORD" -out "$WORKDIR/signing.p12")
openssl "${p12_args[@]}" -macalg sha1 2>/dev/null || openssl "${p12_args[@]}"
openssl pkcs12 -in "$WORKDIR/signing.p12" -passin "pass:$CSC_KEY_PASSWORD" -nokeys 2>/dev/null |
  grep -q "Developer ID Application" || { warn "could not build a valid .p12"; exit 1; }
set_secret CSC_LINK "$(base64 < "$WORKDIR/signing.p12" | tr -d '\n')"
set_secret CSC_KEY_PASSWORD "$CSC_KEY_PASSWORD"

stage "Create the Developer ID provisioning profile"
open_url "https://developer.apple.com/account/resources/profiles/add"
step "Under Distribution choose Developer ID, Continue."
step "App ID: $APP_ID, Continue."
step "Select the Developer ID Application certificate you just made, Continue."
step "Name it T3 Code V2 Developer ID, Generate, then Download."
ask_file PROFILE_PATH "Path to the downloaded .provisionprofile:"
write_env PROFILE_PATH "$PROFILE_PATH"
set_secret MACOS_PROVISIONING_PROFILE "$(base64 < "$PROFILE_PATH" | tr -d '\n')"

stage "Create the notarization API key"
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Open the Team Keys tab. (First time: the Account Holder clicks Request Access.)"
step "Click + , Name: T3 Code V2 notarization, Access: Developer, Generate."
step "Copy the Issuer ID shown above the keys table, and the new key's Key ID."
step "Click Download on the key. Apple lets you download it only once."
ask APPLE_API_ISSUER "Issuer ID:"
write_env APPLE_API_ISSUER "$APPLE_API_ISSUER"
ask APPLE_API_KEY_ID "Key ID:"
write_env APPLE_API_KEY_ID "$APPLE_API_KEY_ID"
ask_file API_KEY_PATH "Path to the downloaded AuthKey_*.p8:"
write_env API_KEY_PATH "$API_KEY_PATH"
set_secret APPLE_API_ISSUER "$APPLE_API_ISSUER"
set_secret APPLE_API_KEY_ID "$APPLE_API_KEY_ID"
set_secret APPLE_API_KEY "$(cat "$API_KEY_PATH")"

stage "Clean up and build"
say "Everything the build needs is now in $REPO's secrets."
warn "$WORKDIR holds your private signing key and the .p8 key in plain files."
note "Keep a copy only if you store it somewhere safe (e.g. a password manager)."
if confirm "Delete $WORKDIR and the downloaded .cer, .provisionprofile, and .p8 now?"; then
  rm -f "$CERT_PATH" "$PROFILE_PATH" "$API_KEY_PATH"
  rm -rf "$WORKDIR"
  printf '  %s✓ deleted%s local key material\n' "$GREEN" "$RESET"
else
  SKIPPED+=("delete $WORKDIR and the downloaded key files once you've stored them safely")
fi
if confirm "Start a signed build now?"; then
  gh workflow run v2-desktop.yml --ref dev -f force=true &&
    note "Started. Watch it at https://github.com/$REPO/actions/workflows/v2-desktop.yml"
fi
pause "Press Enter to finish"

finish
